### ISSUE TITLE
Monetary value?

### ISSUE THREAD

**Issue by dayaki** [zgabievi/Promocodes#1]
Hi, thanks for this awesome package. I have plans to include this in a project am working on but I want to understand how can i tweak your code if i want the generated codes to be attached to monetary value. Say how itunes gift card work.

**Comment by zgabievi** [comment]
Hi @dayaki.
Sorry for late reply.
I hadn't planned to work on monetary value. But I like that idea and I think that I will work on that for next version.

**Comment by dayaki** [comment]
@zgabievi Thanks, any timeline as to when you can work on this? Could you give me directions on how I can implement this? as i love to include this in an ongoing project.

Thanks

**Comment by zgabievi** [comment]
@dayaki easies way to implement this is to use if condition. If I understood you correctly you can do something like this:

```php
$applied = Promocodes::apply('TEST-CODE');

if ($applied) {
    // do some action. give user something ))
}
```

**Comment by dayaki** [comment]
Thanks, sent you an email.

**Comment by zgabievi** [comment]
Oh, now I see. Great idea. I will work on that today. And will inform you about updates. Thank you for this idea

**Comment by dayaki** [comment]
Thanks so much, will be expecting

**Comment by zgabievi** [comment]
There you go, you can check Readme.md now.

**Comment by dayaki** [comment]
Awesome man, do i need to update/reinstall your package to make use of the changes? because I did `composer update` and your package didnt update

**Comment by zgabievi** [comment]
You need to update to 0.1.2 version

**Comment by zgabievi** [comment]
@dayaki Can we close this issue?

**Comment by dayaki** [comment]
am getting this error:

![screen-shot-2016-05-20-at-11 47 35-am](https://cloud.githubusercontent.com/assets/815619/15425536/d031ac20-1e80-11e6-911e-ec8358db27e3.jpg)

**Comment by zgabievi** [comment]
Sorry, there was symbol mistake :/ I've fixed that

**Comment by dayaki** [comment]
Whenever i try to save a code using `Promocodes::save(5, 10.50)`, i keep getting `SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '10.5' for key 'promocodes_code_unique' (SQL: insert into `promocodes` (`code`) values (GT16-P8PBTF-CYY6W), (10.5), (GT16-ZNA410-TAJNN), (10.5), (GT16-U9NHAJ-ZUB4R), (10.5), (GT16-7DFYUF-9W5MX), (10.5), (GT16-38ATM9-KR3KM), (10.5))` error

**Comment by zgabievi** [comment]
Here we go. I've tested some cases with tinker. Here is screenshot of this test:

![image](https://cloud.githubusercontent.com/assets/1515299/15606935/24da2500-2420-11e6-850b-e6ce76001939.png)

Please, update to 0.1.4.

**Comment by dayaki** [comment]
Thanks, its working now, BUT you missed  a`]` in line 144 of Promocodes.php. It is `$data[$key['reward'] = $reward;` instead of `$data[$key]['reward'] = $reward;`

**Comment by zgabievi** [comment]
Fixed, thanks. I'm so bad today :D I will close issue for now. ;)
